source 'https://github.com/wax2045/NNSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NNHomeKit_category_Example' do
  pod 'NNHomeKit_category', :path => '../'

  target 'NNHomeKit_category_Tests' do
    inherit! :search_paths

    
  end
end
